const sBlock = [
  { symbol: "H", atomicNumber: 1, block: "s", group: "1", period: "1" },
  { symbol: "He", atomicNumber: 2, block: "s", group: "18", period: "1" },
  { symbol: "Li", atomicNumber: 3, block: "s", group: "1", period: "2" },
  { symbol: "Be", atomicNumber: 4, block: "s", group: "2", period: "2" },
  { symbol: "Na", atomicNumber: 11, block: "s", group: "1", period: "3" },
  { symbol: "Mg", atomicNumber: 12, block: "s", group: "2", period: "3" },
  { symbol: "K", atomicNumber: 19, block: "s", group: "1", period: "4" },
  { symbol: "Ca", atomicNumber: 20, block: "s", group: "2", period: "4" },
  { symbol: "Rb", atomicNumber: 37, block: "s", group: "1", period: "5" },
  { symbol: "Sr", atomicNumber: 38, block: "s", group: "2", period: "5" },
  { symbol: "Cs", atomicNumber: 55, block: "s", group: "1", period: "6" },
  { symbol: "Ba", atomicNumber: 56, block: "s", group: "2", period: "6" },
  { symbol: "Fr", atomicNumber: 87, block: "s", group: "1", period: "7" },
  { symbol: "Ra", atomicNumber: 88, block: "s", group: "2", period: "7" },
];
// ///////////////////////////////////////////// p block /////////////////////////////////////////////////

const pBlock = [
  { symbol: "B", atomicNumber: 5, block: "p", group: "13", period: "2" },
  { symbol: "C", atomicNumber: 6, block: "p", group: "14", period: "2" },
  { symbol: "N", atomicNumber: 7, block: "p", group: "15", period: "2" },
  { symbol: "O", atomicNumber: 8, block: "p", group: "16", period: "2" },
  { symbol: "F", atomicNumber: 9, block: "p", group: "17", period: "2" },
  { symbol: "Ne", atomicNumber: 10, block: "p", group: "18", period: "2" },
  { symbol: "Al", atomicNumber: 13, block: "p", group: "13", period: "3" },
  { symbol: "Si", atomicNumber: 14, block: "p", group: "14", period: "3" },
  { symbol: "P", atomicNumber: 15, block: "p", group: "15", period: "3" },
  { symbol: "S", atomicNumber: 16, block: "p", group: "16", period: "3" },
  { symbol: "Cl", atomicNumber: 17, block: "p", group: "17", period: "3" },
  { symbol: "Ar", atomicNumber: 18, block: "p", group: "18", period: "3" },
  { symbol: "Ga", atomicNumber: 31, block: "p", group: "13", period: "4" },
  { symbol: "Ge", atomicNumber: 32, block: "p", group: "14", period: "4" },
  { symbol: "As", atomicNumber: 33, block: "p", group: "15", period: "4" },
  { symbol: "Se", atomicNumber: 34, block: "p", group: "16", period: "4" },
  { symbol: "Br", atomicNumber: 35, block: "p", group: "17", period: "4" },
  { symbol: "Kr", atomicNumber: 36, block: "p", group: "18", period: "4" },
  { symbol: "In", atomicNumber: 49, block: "p", group: "13", period: "5" },
  { symbol: "Sn", atomicNumber: 50, block: "p", group: "14", period: "5" },
  { symbol: "Sb", atomicNumber: 51, block: "p", group: "15", period: "5" },
  { symbol: "Te", atomicNumber: 52, block: "p", group: "16", period: "5" },
  { symbol: "I", atomicNumber: 53, block: "p", group: "17", period: "5" },
  { symbol: "Xe", atomicNumber: 54, block: "p", group: "18", period: "5" },
  { symbol: "Tl", atomicNumber: 81, block: "p", group: "13", period: "6" },
  { symbol: "Pb", atomicNumber: 82, block: "p", group: "14", period: "6" },
  { symbol: "Bi", atomicNumber: 83, block: "p", group: "15", period: "6" },
  { symbol: "Po", atomicNumber: 84, block: "p", group: "16", period: "6" },
  { symbol: "At", atomicNumber: 85, block: "p", group: "17", period: "6" },
  { symbol: "Rn", atomicNumber: 86, block: "p", group: "18", period: "6" },
  { symbol: "Nh", atomicNumber: 113, block: "p", group: "13", period: "7" },
  { symbol: "Fl", atomicNumber: 114, block: "p", group: "14", period: "7" },
  { symbol: "Mc", atomicNumber: 115, block: "p", group: "15", period: "7" },
  { symbol: "Lv", atomicNumber: 116, block: "p", group: "16", period: "7" },
  { symbol: "Ts", atomicNumber: 117, block: "p", group: "17", period: "7" },
  { symbol: "Og", atomicNumber: 118, block: "p", group: "18", period: "7" },
];
// ///////////////////////////////////////////// d block /////////////////////////////////////////////////

const dBlock = [
  { symbol: "Sc", atomicNumber: 21, block: "d", group: "3", period: "4" },
  { symbol: "Ti", atomicNumber: 22, block: "d", group: "4", period: "4" },
  { symbol: "V", atomicNumber: 23, block: "d", group: "5", period: "4" },
  { symbol: "Cr", atomicNumber: 24, block: "d", group: "6", period: "4" },
  { symbol: "Mn", atomicNumber: 25, block: "d", group: "7", period: "4" },
  { symbol: "Fe", atomicNumber: 26, block: "d", group: "8", period: "4" },
  { symbol: "Co", atomicNumber: 27, block: "d", group: "9", period: "4" },
  { symbol: "Ni", atomicNumber: 28, block: "d", group: "10", period: "4" },
  { symbol: "Cu", atomicNumber: 29, block: "d", group: "11", period: "4" },
  { symbol: "Zn", atomicNumber: 30, block: "d", group: "12", period: "4" },
  { symbol: "Y", atomicNumber: 39, block: "d", group: "3", period: "5" },
  { symbol: "Zr", atomicNumber: 40, block: "d", group: "4", period: "5" },
  { symbol: "Nb", atomicNumber: 41, block: "d", group: "5", period: "5" },
  { symbol: "Mo", atomicNumber: 42, block: "d", group: "6", period: "5" },
  { symbol: "Tc", atomicNumber: 43, block: "d", group: "7", period: "5" },
  { symbol: "Ru", atomicNumber: 44, block: "d", group: "8", period: "5" },
  { symbol: "Rh", atomicNumber: 45, block: "d", group: "9", period: "5" },
  { symbol: "Pd", atomicNumber: 46, block: "d", group: "10", period: "5" },
  { symbol: "Ag", atomicNumber: 47, block: "d", group: "11", period: "5" },
  { symbol: "Cd", atomicNumber: 48, block: "d", group: "12", period: "5" },
  { symbol: "Lu", atomicNumber: 71, block: "d", group: "3", period: "6" },
  { symbol: "Hf", atomicNumber: 72, block: "d", group: "4", period: "6" },
  { symbol: "Ta", atomicNumber: 73, block: "d", group: "5", period: "6" },
  { symbol: "W", atomicNumber: 74, block: "d", group: "6", period: "6" },
  { symbol: "Re", atomicNumber: 75, block: "d", group: "7", period: "6" },
  { symbol: "Os", atomicNumber: 76, block: "d", group: "8", period: "6" },
  { symbol: "Ir", atomicNumber: 77, block: "d", group: "9", period: "6" },
  { symbol: "Pt", atomicNumber: 78, block: "d", group: "10", period: "6" },
  { symbol: "Au", atomicNumber: 79, block: "d", group: "11", period: "6" },
  { symbol: "Hg", atomicNumber: 80, block: "d", group: "12", period: "6" },
  { symbol: "Lr", atomicNumber: 103, block: "d", group: "3", period: "7" },
  { symbol: "Rf", atomicNumber: 104, block: "d", group: "4", period: "7" },
  { symbol: "Db", atomicNumber: 105, block: "d", group: "5", period: "7" },
  { symbol: "Sg", atomicNumber: 106, block: "d", group: "6", period: "7" },
  { symbol: "Bh", atomicNumber: 107, block: "d", group: "7", period: "7" },
  { symbol: "Hs", atomicNumber: 108, block: "d", group: "8", period: "7" },
  { symbol: "Mt", atomicNumber: 109, block: "d", group: "9", period: "7" },
  { symbol: "Ds", atomicNumber: 110, block: "d", group: "10", period: "7" },
  { symbol: "Rg", atomicNumber: 111, block: "d", group: "11", period: "7" },
  { symbol: "Cn", atomicNumber: 112, block: "d", group: "12", period: "7" },
];
// ///////////////////////////////////////////// f block /////////////////////////////////////////////////
const fBlock = [
  { symbol: "La", atomicNumber: 57, block: "f", group: "3", period: "6" },
  { symbol: "Ce", atomicNumber: 58, block: "f", group: "3", period: "6" },
  { symbol: "Pr", atomicNumber: 59, block: "f", group: "3", period: "6" },
  { symbol: "Nd", atomicNumber: 60, block: "f", group: "3", period: "6" },
  { symbol: "Pm", atomicNumber: 61, block: "f", group: "3", period: "6" },
  { symbol: "Sm", atomicNumber: 62, block: "f", group: "3", period: "6" },
  { symbol: "Eu", atomicNumber: 63, block: "f", group: "3", period: "6" },
  { symbol: "Gd", atomicNumber: 64, block: "f", group: "3", period: "6" },
  { symbol: "Tb", atomicNumber: 65, block: "f", group: "3", period: "6" },
  { symbol: "Dy", atomicNumber: 66, block: "f", group: "3", period: "6" },
  { symbol: "Ho", atomicNumber: 67, block: "f", group: "3", period: "6" },
  { symbol: "Er", atomicNumber: 68, block: "f", group: "3", period: "6" },
  { symbol: "Tm", atomicNumber: 69, block: "f", group: "3", period: "6" },
  { symbol: "Yb", atomicNumber: 70, block: "f", group: "3", period: "6" },
  { symbol: "Ac", atomicNumber: 89, block: "f", group: "3", period: "7" },
  { symbol: "Th", atomicNumber: 90, block: "f", group: "3", period: "7" },
  { symbol: "Pa", atomicNumber: 91, block: "f", group: "3", period: "7" },
  { symbol: "U", atomicNumber: 92, block: "f", group: "3", period: "7" },
  { symbol: "Np", atomicNumber: 93, block: "f", group: "3", period: "7" },
  { symbol: "Pu", atomicNumber: 94, block: "f", group: "3", period: "7" },
  { symbol: "Am", atomicNumber: 95, block: "f", group: "3", period: "7" },
  { symbol: "Cm", atomicNumber: 96, block: "f", group: "3", period: "7" },
  { symbol: "Bk", atomicNumber: 97, block: "f", group: "3", period: "7" },
  { symbol: "Cf", atomicNumber: 98, block: "f", group: "3", period: "7" },
  { symbol: "Es", atomicNumber: 99, block: "f", group: "3", period: "7" },
  { symbol: "Fm", atomicNumber: 100, block: "f", group: "3", period: "7" },
  { symbol: "Md", atomicNumber: 101, block: "f", group: "3", period: "7" },
  { symbol: "No", atomicNumber: 102, block: "f", group: "3", period: "7" },
];

module.exports = { sBlock, pBlock, dBlock, fBlock };
